# Generated by Django 5.2 on 2025-05-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_imageurl_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images'),
        ),
    ]
