# Generated by Django 5.2 on 2025-06-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_image_alter_uploadmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='timetable',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
